#  extend from base amazon/amazon-ecs-sample:latest
FROM amazon/amazon-ecs-sample:latest
# do something neglible to change the SHA
RUN echo "Customized ECS Sample Image with tag release-1.0.10" > /etc/custom_info.txt